name: "build the ci"

on: [push,workflow_dispatch]


jobs:
  build:
    name: "build the images"
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v4
      - name: "install python "
        uses: actions/setup-python@v1
      - name: setup docker
        uses: docker/setup-buildx-action@v3

      - name: "azure login"
        uses: azure/login@v1
        with:
          creds: ${{ vars.AZURE_CRED }}

      - name: Login to azure container resigtry
        run: az acr login --name ${{ vars.ACR_NAME }}

      - name: build the docker image
        
        run: |
          pwd
          docker build -t neha/demo:latest python-jenkins-argocd-k8s/.
  
